using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO;
using System.Linq;

namespace OwlApi.Helpers
{
    public class RunCmd
    {
        public string Run(string program, string cmd, string[] args)
        {
            ProcessStartInfo start = new ProcessStartInfo();
            start.FileName = program;
            start.Arguments = string.Format("\"{0}\" {1}", cmd, string.Join(" ", new List<string>(args).Select(arg => $"\"{arg.Replace("\"", "\"\"")}\"")));
            start.UseShellExecute = false;// Do not use OS shell
            start.CreateNoWindow = true; // We don't need new window
            start.RedirectStandardOutput = true;// Any output, generated by application will be redirected back
            start.RedirectStandardError = true; // Any error in standard output will be redirected back (for example exceptions)
            using (Process process = Process.Start(start))
            {
                process.WaitForExit();
                using (StreamReader reader = process.StandardOutput)
                {
                    string stderr = process.StandardError.ReadToEnd(); // Here are the exceptions from our Python script
                    if (process.ExitCode != 0 && stderr != null && stderr.Trim().Length > 0)
                    {
                        throw new ApplicationException(stderr);
                    }

                    string result = reader.ReadToEnd(); // Here is the result of StdOut(for example: print "test")
                    return result;
                }
            }
        }
    }
}